CREATE TABLE users(
	email VARCHAR(200) NOT NULL PRIMARY KEY,
	firstname VARCHAR(50) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	phonenumber VARCHAR(13) NOT NULL UNIQUE,
	userpassword VARCHAR(200) NOT NULL
);

CREATE TABLE laptop(
	laptopid VARCHAR(10) NOT NULL PRIMARY KEY,
	laptopImage VARCHAR(1000) NOT NULL,
	laptopname VARCHAR(100) NOT NULL,
	laptopprice DECIMAL(8,2) NOT NULL,
	laptopcategory VARCHAR(100) NOT NULL,
	cpu VARCHAR(200) NOT NULL,
	ram VARCHAR(200) NOT NULL,
	storage VARCHAR(200) NOT NULL,
	graphiccard VARCHAR(200)
);

CREATE TABLE ORDERS(
      ORDERID VARCHAR(10) NOT NULL PRIMARY KEY,
      LAPTOPID VARCHAR(10) NOT NULL,
      QUANTITY INTEGER,
      STATUS VARCHAR(40) NOT NULL,
      ORDERDATE DATE,
      EMAIL VARCHAR(200) NOT NULL,
      ADDRESS VARCHAR(255) NOT NULL,
      PRICE DECIMAL(8,2) NOT NULL,
      FOREIGN KEY ("LAPTOPID") REFERENCES LAPTOP("LAPTOPID"),
      FOREIGN KEY ("EMAIL") REFERENCES USERS("EMAIL")
);

CREATE TABLE "PAYMENTCARD"(
    "CARDNUMBER" VARCHAR(20) NOT NULL PRIMARY KEY,
    "BALANCE" DECIMAL(8,2)
);

CREATE TABLE TECHNETUSER(
	technetID VARCHAR (4) NOT NULL PRIMARY KEY,
	firstname VARCHAR(50) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	technetPassword VARCHAR(200) NOT NULL
);

CREATE TABLE ADMINCOMMENT(
     commentID  VARCHAR (4) NOT NULL PRIMARY KEY,
     technetID VARCHAR (4) NOT NULL,
     comment VARCHAR(300) NOT NULL,
     FOREIGN KEY ("TECHNETID") REFERENCES TECHNETUSER("TECHNETID")
);
